# Generated by Django 4.0 on 2025-11-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(upload_to='Movie2Poster/')),
                ('year', models.IntegerField(default=2025)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='upcoming/')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
