# Generated by Django 4.0 on 2025-11-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie2_upcoming_movie_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
