# Generated by Django 4.0 on 2025-11-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_upcoming_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
